Add first version of git templating functions

diff --git a/bash_functions.d/git b/bash_functions.d/git
--- a/bash_functions.d/git
+++ b/bash_functions.d/git
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+GIT_TEMPLATE_DIR=~/.git_templates
+
 git_branch_checkout_fzf() {
     local branches branch
 
@@ -34,4 +36,54 @@ git_checkout_fzf() {
     if [[ $checkout_target ]]; then
         git checkout "$(echo "$checkout_target" | awk '{print $1}' | sed "s/.* //")"
     fi
+}
+
+git_create_branch_with_template() {
+    local template=$1
+    local template_file branch_to_create
+
+    if [[ $# -lt 1 ]]; then
+        echo "At least a template must be specified" 1>&2
+        return 1
+    fi
+
+    template_file="${GIT_TEMPLATE_DIR}/${template}"
+    if [[ ! -f "$template_file" ]]; then
+        echo "Template file for \"$template\" not found in \"$GIT_TEMPLATE_DIR\"" 1>&2
+        return 1
+    fi
+
+    source "$template_file"
+
+    shift
+
+    branch_to_create=$(branch_template "$@")
+    git checkout -b "$branch_to_create" --track
+}
+
+git_create_commit_with_template() {
+    local template=$1
+    local template_file commit_message
+
+    if [[ $# -lt 1 ]]; then
+        echo "At least a template must be specified" 1>&2
+        return 1
+    fi
+
+    template_file="${GIT_TEMPLATE_DIR}/${template}"
+    if [[ ! -f "$template_file" ]]; then
+        echo "Template file for \"$template\" not found in \"$GIT_TEMPLATE_DIR\"" 1>&2
+        return 1
+    fi
+
+    source "$template_file"
+
+    shift
+
+    commit_message=$(commit_template "$@")
+    git commit --edit --message "$commit_message"
+}
+
+git_get_current_branch() {
+    git branch --list | grep '^*' | awk '{ print $2 }'
 }
